# -*- coding: utf-8 -*-
"""average_Ratings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_aAjMLGaaNzcy_ib3lRD4x3H0S3Dpcyi
"""

import pandas as pd

#input: a csv file containing the input ratings
#returns a dataframe containing the average ratings for each response
def average_ratings(ratings):
  df = pd.read_csv('Fake-Data-2-Sheet1.csv')
  avg = df[['QuestionToBeRated1','Response1','R1Rated']].rename(columns={'QuestionToBeRated1': 'Question', 'Response1': 'Response', 'R1Rated':'rating'})
  for i in range(2,6):
    avg = avg.append(df[['QuestionToBeRated' + str(i),'Response' + str(i),'R' + str(i) + 'Rated']].rename(columns={'QuestionToBeRated' + str(i): 'Question', 'Response'  + str(i): 'Response', 'R' + str(i) + 'Rated':'rating'}))
  avg = avg.groupby(by=['Question','Response']).mean()
  return avg
average_ratings('Fake-Data-2-Sheet1.csv')